---
# https://taskfile.dev/

version: '3'

tasks:
  init:
    - task: install
    - task: helm install vidra-operator oci://ghcr.io/infrahub-operator/vidra/helm-charts/vidra-operator --namespace vidra-system --create-namespace
    - |
      while ! curl -s http://localhost:8000 > /dev/null; do
        echo "Waiting for localhost:8000 to be available..."
        sleep 5
      done
    - task: start

  install:
    cmds:
      - docker compose up
    desc: Start Infrahub
  start:
    cmds:
      - python3 python_scripts/startscript.py
      - task startweb
    desc: Load data in Infrahub and Start Webserver
  startweb:
    cmds:
      - poetry run python3 webserver/webserver.py
    desc: Start Webserver
  destroy:
    cmds:
      - docker compose down
      - docker system prune -a
      - docker volume prune -a
    desc: Delete the Infrahub Server
  default:
    cmds:
      - task --list-all
