mutation CreateWebserver ($name:String!, $description:String!, $namespace:String!, $image:String!) {
  KubernetesWebserverCreate(
    data: {
        object_template: {hfid: "tem-webserver"},
        name: {value: $name},
        description: {value: $description},
        namespace: {value: $namespace},
        image: {value: $image},
        member_of_groups: {hfid: "g_webserver"}
    }
  ) {
    object {
      host {
        value
      }
    }
  }
}